name: Upload rosiekerwinresume.com frontend files to S3

on:
  push:
    branches:
    - main

jobs:
  deploy-to-s3:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@main
    - uses: jakejarvis/s3-sync-action@master
      with:
        args: --delete --exclude frontend/tests
      env:
        AWS_S3_BUCKET: ${{ secrets.AWS_S3_BUCKET }}
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        AWS_REGION: 'us-east-1'
        SOURCE_DIR: 'frontend'

  cypress-run:
    name: Run Cypress smoke tests on deployed website
    runs-on: ubuntu-latest
    needs:
      - deploy-to-s3
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v3
      - name: Cypress run
        uses: cypress-io/github-action@v6
        with:
          project: ./frontend/tests
